# Clase 11: Functions

In [75]:
#Si necesitamos repetir cálculos continuamente. Es un código que corre solo cuando lo llamas

In [76]:
#función que calcula las ventas promedio
def precio_promedio(venta_total,numero_articulos):
    promedio=venta_total/numero_articulos
    return promedio

In [78]:
precio_promedio(500,20)

25.0

In [81]:
venta=10
piezas=10

In [82]:
precio_promedio(venta,piezas)

1.0

### Arrays

In [83]:
# arrays una variable especial que contiene más de una variable y hace que los cálculos se ejecuten de manera eficientemente rápida

In [84]:
#lo primero es importar la librería de numpy
import numpy as np

In [86]:
resultados_1=np.array([100,34])
resultados_2=np.array([150,40])
resultados_3=np.array([200,54])

In [87]:
venta_3años=resultados_1+resultados_2+resultados_3

In [88]:
venta_3años

array([450, 128])

In [89]:
resultados_1*2


array([200,  68])

In [90]:
resultados_2/3

array([50.        , 13.33333333])

In [91]:
resultados_3+54

array([254, 108])